# @package _global_
defaults:
    - override /datasets: traj


tokenizers:
    states:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create
    actions:
      _target_: research.mtm.tokenizers.discrete_identity.DiscreteIdentity.create
      num_classes: 1000  # Example: Number of discrete action classe (poi types)
wandb:
    project: "traj"
    resume: False
