# @package _global_
defaults:
    - override /datasets: traj


tokenizers:
    states:
      _target_: research.mtm.tokenizers.discrete_identity.DiscreteIdentity.create
    actions:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create

wandb:
    project: "traj"
    resume: False
