# @package _global_
defaults:
    - override /datasets: traj

tokenizers:
    states:
      _target_: research.mtm.tokenizers.discrete_identity.DiscreteIdentity.create
      num_classes: 198   # Add the num_classes parameter 
    actions:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create

wandb:
    project: "traj"
    resume: False
