# @package _global_
defaults:
    - override /datasets: traj_01_04


tokenizers:
    states:
      _target_: research.mtm.tokenizers.uniform_bins.UniformBinningTokenizer.create
      num_bins: 64
    actions:
      _target_: research.mtm.tokenizers.uniform_bins.UniformBinningTokenizer.create
      num_bins: 64
    rewards:
      _target_: research.mtm.tokenizers.uniform_bins.UniformBinningTokenizer.create
      num_bins: 64

dataset:
    use_rewards: False

wandb:
    project: "traj_01_04"
    resume: allow
